config/routes.rb
Rails.application.routes.draw do
  get 'workouts/friends' => 'workouts#friends'
  get 'workouts/summary' => 'workouts#summary'
  
  resources :workouts
  devise_for :users
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :all_workouts, only: [:index, :create, :update, :destroy]
  before_action :set_workouts, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def index
    @workouts = Workout.all
  
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @workout = Workout.new
  end
  
  def update
    @workout.update_attributes(workout_params)
  end

  def create
    @workout  = Workout.create(workout_params)
  end
  
  def destroy
    @workout.destroy
  end

  private

    def all_workouts
      @workouts = Workout.all
    end
    
    def set_workouts
      @workout = Workout.find(params[:id])
    end

    def workout_params
      params.require(:workout).permit(:description, :workout_date, :completed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_nav.html.erb
<%= nav_bar brand: "Brand", responsive: true do %>
    <%= menu_group do %>
        <%= drop_down "Workouts" do %>
            <%= menu_item "My Workouts", workouts_path %>
            <%= menu_item "Friend's Workouts", workouts_friends_path %>
            <%= menu_item "Summary", workouts_summary_path %>
        <% end %>
    <% end %>
    <%= menu_group pull: :right do %>
        <% if current_user %>
            <%= menu_item "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= menu_item "Sign in", new_user_session_path %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <%= render "layouts/nav" %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash id: "FlashBootstrap" %>
          <div id="content">
            <%= yield %>
          </div>
          
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav" id="sidebar">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer id="footer">
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1>Workech Landing page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/workouts/_form.html.erb
<%= form_for @workout, remote: true, :html => { :class => "form-horizontal workout" } do |f| %>

  <% if @workout.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :workout_date, :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field :workout_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:workout_date) %>
  </div>
  <div class="form-group">
    <%= f.label :completed, :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field :completed, :class => 'form-control' %>
    </div>
    <%=f.error_span(:completed) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                workouts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/workouts/_workout.html.erb
<tr>
  <td><%= link_to workout.id, workout_path(workout) %></td>
  <td><%= workout.description %></td>
  <td><%= workout.workout_date %></td>
  <td><%= workout.completed %></td>
  <td><%= workout.user_id %></td>
  <td><%=l workout.created_at %></td>
  <td>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_workout_path(workout), :class => 'btn btn-default btn-xs', remote: true %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          workout_path(workout),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger', remote: true%>
  </td>
</tr>

app/views/workouts/create.js.erb
$('#workouts').html("<%= j (render @workouts) %>");
$('#workout-form').slideUp(350);

app/views/workouts/destroy.js.erb
$('#workouts').html("<%= j (render @workouts) %>");

app/views/workouts/edit.js.erb
$('#workout-form').html("<%= j (render 'form') %>");
$('#workout-form').slideDown(350);

app/views/workouts/friends.html.erb
<h1>Friend's Workouts</h1>

app/views/workouts/index.html.erb
<%- model_class = Workout -%>
<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <h2>My Workouts</h2>
  </div>

  <div class="col-md-2">
    <%= link_to new_workout_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-md-8 col-md-offset-2" id="workout-form" style="display:none;"></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:workout) %></th>
      <th><%= model_class.human_attribute_name(:workout_date) %></th>
      <th><%= model_class.human_attribute_name(:completed) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="workouts">
    <%= render @workouts %>
  </tbody>
</table>

app/views/workouts/new.js.erb
$('#workout-form').html("<%= j (render 'form') %>");
$('#workout-form').slideDown(350);

app/views/workouts/summary.html.erb
<h1>Workouts Summary</h1>

app/views/workouts/update.js.erb
$('#workout-form').html("<%= j (render 'form') %>");
$('#workout-form').slideDown(350);